---
resources:
- name: pal-tracker
  type: git
  source:
    uri: {{github-repository}}
    branch: master
    private_key: {{github-private-key}}

- name: pal-tracker-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: releases/pal-tracker-(.*).jar
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: pal-tracker/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: review-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: review

- name: production-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: production

jobs:
- name: build
  plan:
  - get: pal-tracker
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build and test
    file: pal-tracker/ci/build.yml
  - put: pal-tracker-artifacts
    params:
      file: build-output/pal-tracker-*.jar
  - put: version
    params:
      file: version/number

- name: deploy-review
  plan:
  - get: pal-tracker
  - get: pal-tracker-artifacts
    trigger: true
    passed: [build]
  - task: migrate database
    file: pal-tracker/ci/migrateDatabase.yml
    params:
      CF_API_URL: https://api.sys.longs.pal.pivotal.io
      CF_USERNAME: pendyala.murthy@wellsfargo.com
      CF_PASSWORD: 8dbnysv3
      CF_ORG: pendyala-murthy
      CF_SPACE: review
      MYSQL_IP: 192.168.16.98
      DATABASE_NAME: cf_360b1825_0b79_46cf_8a1a_9231d91a60af
      DATABASE_USERNAME: pZRgdto1eaNI96xz
      DATABASE_PASSWORD: t5wbCHrQWfa9CT6c
  - put: review-deployment
    params:
      manifest: pal-tracker/manifest-review.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar
      environment_variables:
        WELCOME_MESSAGE: "Hello from the review environment"

- name: deploy-production
  plan:
  - get: pal-tracker
  - get: pal-tracker-artifacts
    passed: [deploy-review]
  - task: migrate database
    file: pal-tracker/ci/migrateDatabase.yml
    params:
      CF_API_URL: https://api.sys.longs.pal.pivotal.io
      CF_USERNAME: pendyala.murthy@wellsfargo.com
      CF_PASSWORD: 8dbnysv3
      CF_ORG: pendyala-murthy
      CF_SPACE: production
      MYSQL_IP: 192.168.16.98
      DATABASE_NAME: cf_08cf23e4_8916_4823_a903_d87e43ba73a0
      DATABASE_USERNAME: M60H45yQfyWU6wGx
      DATABASE_PASSWORD: 3XWVOXtjA5md4iM7
  - put: production-deployment
    params:
      manifest: pal-tracker/manifest-production.yml
      path: pal-tracker-artifacts/pal-tracker-*.jar
      environment_variables:
        WELCOME_MESSAGE: "Hello from the production environment"